import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/legacy/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <>
      <div className={darkMode ? 'dark' : ''}>

        <Head>
          <title>Bruno Possiedi Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link href="../" rel="stylesheet"></link>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
          <section>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-gray-300'>Bruno Possiedi</h1>
              <ul className='flex item-center'>
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursos-pointer text-2xl dark:text-white'/>
                </li>
                <li>
                  <a href="https://www.notion.so/Bruno-Alexandre-Possiedi-da-Silva-a1ac4b76b29643859a9ee509c2b20c6a" className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a>
                </li>
              </ul>
            </nav>

            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-200'>Bruno Possiedi</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-300'>Developer.</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl dark:text-gray-400'>Site feito com React e Tailwind para demonstração.</p>
            </div>

            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-white'>
              <a href="https://www.linkedin.com/in/brunopossiedi/"><AiFillLinkedin/></a>
              <a href='https://github.com/brunooaps'><AiFillGithub/></a>
            </div>

            {/* <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={deved} layout="fill" objectFit="cover"/>
            </div> */}
          </section>

          <section>
            <div>
              <h3 className='text-3xl py-1 dark:text-white'>Sobre mim</h3>
              <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-300'>Eu sou um desenvolvedor web com 3 anos de experiência em programação, especializado em PHP Laravel, ReactJS e VueJS. Além disso, atualmente estou estudando Engenharia de Software para aprimorar meus conhecimentos na área. Meu objetivo é criar soluções inovadoras e eficientes que atendam às necessidades dos usuários finais, aplicando as melhores práticas de desenvolvimento e trabalhando em equipe para alcançar resultados de alta qualidade. Estou sempre em busca de novos desafios e oportunidades para crescer profissionalmente.</p>
            </div>
            <div className='lg:flex justify-center gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-gray-600'>
                <Image src={code} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Fullstack development</h3>
                <p className='py-2 dark:text-gray-300 w-96'>Durante 1 ano fiz um projeto de gestão de usuários para o Hospital Pequeno Príncipe, onde o intúito era buscar e inserir dados nos bancos de dados PostgreSQL da instituição.</p>
                <h4 className='py-4 text-teal-600 dark:text-teal-200'>Ferramentas utilizadas</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Laravel</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>React-Admin</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Git</p>
              </div>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:shadow-gray-600'>
                <Image src={code} width={100} height={100}/>
                <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Front-end development</h3>
                <p className='py-2 dark:text-gray-300 w-96'>Participei de um projeto para fazer um ecommerce junto com varios outros desenvolvedores.</p>
                <h4 className='py-4 text-teal-600 dark:text-teal-200'>Ferramentas utilizadas</h4>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Laravel</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>VueJS</p>
                <p className='text-gray-800 py-1 dark:text-gray-400'>Git</p>
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
